version: '3.7'


services:
  db:
    image: postgres:10.1
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=authz
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432